export const oracleAbi = [
  {
     "type":"constructor",
     "inputs":[
        {
           "name":"domain",
           "type":"string",
           "internalType":"string"
        },
        {
           "name":"inRoflAppID",
           "type":"bytes21",
           "internalType":"bytes21"
        },
        {
           "name":"inOracle",
           "type":"address",
           "internalType":"address"
        }
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"appendPrompt",
     "inputs":[
        {
           "name":"prompt",
           "type":"string",
           "internalType":"string"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"clearPrompt",
     "inputs":[
        
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"domain",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"string",
           "internalType":"string"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"getAnswers",
     "inputs":[
        {
           "name":"authToken",
           "type":"bytes",
           "internalType":"bytes"
        },
        {
           "name":"addr",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"tuple[]",
           "internalType":"struct Answer[]",
           "components":[
              {
                 "name":"promptId",
                 "type":"uint256",
                 "internalType":"uint256"
              },
              {
                 "name":"answer",
                 "type":"string",
                 "internalType":"string"
              }
           ]
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"getPrompts",
     "inputs":[
        {
           "name":"authToken",
           "type":"bytes",
           "internalType":"bytes"
        },
        {
           "name":"addr",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"string[]",
           "internalType":"string[]"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"getPromptsCount",
     "inputs":[
        {
           "name":"authToken",
           "type":"bytes",
           "internalType":"bytes"
        },
        {
           "name":"addr",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"login",
     "inputs":[
        {
           "name":"siweMsg",
           "type":"string",
           "internalType":"string"
        },
        {
           "name":"sig",
           "type":"tuple",
           "internalType":"struct SignatureRSV",
           "components":[
              {
                 "name":"r",
                 "type":"bytes32",
                 "internalType":"bytes32"
              },
              {
                 "name":"s",
                 "type":"bytes32",
                 "internalType":"bytes32"
              },
              {
                 "name":"v",
                 "type":"uint256",
                 "internalType":"uint256"
              }
           ]
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"bytes",
           "internalType":"bytes"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"oracle",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"address",
           "internalType":"address"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"roflAppID",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"bytes21",
           "internalType":"bytes21"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"setOracle",
     "inputs":[
        {
           "name":"addr",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"submitAnswer",
     "inputs":[
        {
           "name":"answer",
           "type":"string",
           "internalType":"string"
        },
        {
           "name":"promptId",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"addr",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"event",
     "name":"AnswerSubmitted",
     "inputs":[
        {
           "name":"sender",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"PromptSubmitted",
     "inputs":[
        {
           "name":"sender",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        }
     ],
     "anonymous":false
  },
  {
     "type":"error",
     "name":"A13e_RevokedAuthToken",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"InvalidPromptId",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"PromptAlreadyAnswered",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"RoflOriginNotAuthorizedForApp",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"SiweAuth_AddressMismatch",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"SiweAuth_ChainIdMismatch",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"SiweAuth_DomainMismatch",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"SiweAuth_Expired",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"SiweAuth_NotBeforeInFuture",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"SiweParser_InvalidAddressLength",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"SiweParser_InvalidNonce",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"SubcallError",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"UnauthorizedOracle",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"UnauthorizedUserOrOracle",
     "inputs":[
        
     ]
  }
] as const;